[package]
name = "hed"
version = "0.1.0"
edition = "2021"
authors = ["shixinhuang99 <shixinhuang99@gmail.com>"]
description = "hosts file editor"
repository = "https://github.com/shixinhuang99/hed"
license = "MIT"
publish = false

[workspace]
members = ["crates/*"]
resolve = "2"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
