[package]
name = "hed"
version = "0.1.0"
edition = "2021"
authors = ["shixinhuang99 <shixinhuang99@gmail.com>"]
description = "hosts file editor"
repository = "https://github.com/shixinhuang99/hed"
license = "MIT"
publish = false

[dependencies]
anyhow = { workspace = true }

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.86"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = [
  "rt",
  "rt-multi-thread",
  "time",
  "macros",
  "sync",
  "fs",
] }

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
