name: Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ${{ matrix.os }}
    name: check (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@v2
        with:
          tool: just,taplo-cli

      - name: Run check
        run: just check

  tests:
    needs: check
    runs-on: ${{ matrix.os }}
    name: tests (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Test code
        run: cargo test
